### ISSUE TITLE
Make the landing page "One Page No Scroll"

### ISSUE THREAD

**Issue by laurogripa** [KappaSigmaMu/kappasigmamu.github.io#54]
The landing page (with the 3d canary) has a problem that it has horizontal and vertical scrolls.

![image](https://user-images.githubusercontent.com/6154932/139606845-a88de9b1-c8e1-416a-9ad9-e4fbec96cf41.png)

It should be a single page without any scrolls

**Comment by edrd-f** [comment]
Is this still valid? On my firefox it shows no scrollbars.

**Comment by laurogripa** [comment]
Solved
